apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: telegraf
    user: ${INFLUXDB_USER}
    password: ${INFLUXDB_PASSWORD}
    isDefault: true
