{
 "title": "Elasticsearch",
 "tags": [ "escluster" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values from elasticsearch_cluster_health with key = \"name\""
   },
   { "name": "policy", "label": "policy", "query": "show retention policies" },
   { "name": "DataSource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Inactive Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_nodes",
     "metrics": [
      {
       "field": "source_node.name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "SELECT max(\"count_total\") - last(\"count_total\") FROM \"elasticsearch_clusterstats_nodes\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_nodes",
     "metrics": [
      {
       "field": "source_node.name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "SELECT last(\"count_total\") FROM \"elasticsearch_clusterstats_nodes\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source_node.name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "measurement": "elasticsearch_cluster_health",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "node_stats.node_master:true",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "unassigned_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "active_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Docs Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Stored data size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Used data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_nodes",
     "query": "SELECT  (last(\"data_0_total_in_bytes\") - last(\"data_0_free_in_bytes\")) / last(\"data_0_total_in_bytes\") * 100  FROM \"elasticsearch_fs\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fs_free_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Health Timeline",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Health Timeline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Shards",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "number" }
   ],
   "targets": [
    {
     "alias": "Primary",
     "bucketAggs": [
      {
       "fake": true,
       "field": "source_node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "metrics": [
      {
       "field": "node_stats.fs.io_stats.total.operations",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type:node_stats",
     "select": [
      [
       { "params": [ "active_primary_shards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Active",
     "bucketAggs": [
      {
       "fake": true,
       "field": "source_node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "metrics": [
      {
       "field": "node_stats.fs.io_stats.total.operations",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type:node_stats",
     "select": [
      [
       { "params": [ "active_shards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average Doc Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lstech_elastic",
     "select": [
      [
       { "params": [ "docsize_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Problematic Shards",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Initializing",
     "bucketAggs": [
      {
       "fake": true,
       "field": "source_node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "metrics": [
      {
       "field": "node_stats.indices.indexing.index_total",
       "id": "1",
       "meta": {
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "type:node_stats",
     "select": [
      [
       { "params": [ "initializing_shards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Unassigned",
     "bucketAggs": [
      {
       "fake": true,
       "field": "source_node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "metrics": [
      {
       "field": "node_stats.indices.indexing.index_total",
       "id": "1",
       "meta": {
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "type:node_stats",
     "select": [
      [
       { "params": [ "unassigned_shards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HTTP Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_http",
     "select": [
      [
       { "params": [ "current_open" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "shards" }
   ],
   "targets": [
    {
     "alias": "Relocating",
     "bucketAggs": [
      {
       "fake": true,
       "field": "source_node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "metrics": [
      {
       "field": "node_stats.process.open_file_descriptors",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type:node_stats",
     "select": [
      [
       { "params": [ "relocating_shards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Indexing rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "doc/sec" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "indexing_index_total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "segments_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_process",
     "select": [
      [
       { "params": [ "open_file_descriptors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Stored Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "SELECT non_negative_derivative(sum(\"indexing_index_time_in_millis\"), $__interval) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Old",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "SELECT non_negative_derivative(sum(\"gc_collectors_old_collection_count\"), 1s) FROM \"elasticsearch_jvm\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(previous) offset 1",
     "select": [
      [
       {
        "params": [
         "gc_collectors_old_collection_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Young",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "SELECT non_negative_derivative(sum(\"gc_collectors_young_collection_count\"), 1s) FROM \"elasticsearch_jvm\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(previous) offset 1",
     "select": [
      [
       {
        "params": [
         "gc_collectors_young_collection_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Run Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       {
        "params": [
         "gc_collectors_old_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Old" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "gc_collectors_young_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Young" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_fs",
     "select": [
      [
       { "params": [ "io_stats_total_operations" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "FieldData Size Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT non_negative_derivative(sum(\"fielddata_memory_size_in_bytes\"), $__interval) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1",
     "select": [
      [
       { "params": [ "fielddata_memory_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_os",
     "select": [
      [
       { "params": [ "cpu_load_average_1m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Cache",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "SELECT non_negative_derivative(sum(\"query_cache_total_count\"), 1s) FROM \"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1",
     "select": [
      [
       { "params": [ "query_cache_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Hit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "SELECT non_negative_derivative(sum(\"query_cache_hit_count\"), 1s) FROM \"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1",
     "select": [
      [
       { "params": [ "query_cache_hit_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Miss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "SELECT non_negative_derivative(sum(\"query_cache_miss_count\"), 1s) FROM \"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1",
     "select": [
      [
       { "params": [ "query_cache_miss_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Merges Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT non_negative_derivative(max(\"merges_total_time_in_millis\"), 1s) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "merges_total_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_max_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "select": [
      [
       { "params": [ "mem_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Get Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT non_negative_derivative(max(\"get_time_in_millis\"), $__interval) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "get_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Max Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "indexing_index_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Search /s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT non_negative_derivative(max(\"search_query_total\"), 1s) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "search_query_total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Merges Current",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "SELECT max(\"merges_current\") FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "merges_current" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Flush Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "flush_total_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Search Fetch Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "search_fetch_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Search Query Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "select": [
      [
       { "params": [ "search_query_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "select": [
      [
       { "params": [ "analyze_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Analyze" ], "type": "alias" }
      ],
      [
       { "params": [ "ccr_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "CCR" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "FetchShard" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "FetchShardStore" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Flush" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "ForceMerge" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Generic" ], "type": "alias" }
      ],
      [
       { "params": [ "get_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Get" ], "type": "alias" }
      ],
      [
       { "params": [ "index_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Index" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Listener" ], "type": "alias" }
      ],
      [
       { "params": [ "management_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Management" ], "type": "alias" }
      ],
      [
       { "params": [ "rollup_indexing_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "RollUPIndexing" ], "type": "alias" }
      ],
      [
       { "params": [ "search_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Search" ], "type": "alias" }
      ],
      [
       { "params": [ "write_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}